version: "3.7"

services:
    runner:
      build:
        context: .
      environment:
        RUNNER_NAME: "my-runner"
        RUNNER_REPOSITORY_URL: https://github.com/dakl/wine
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock