name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          docker build -t wine .
          dvc pull

          docker run -v data:/app/data wine > report.md
          cat report.md