name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build -t wine .

      - name: run
        run: docker run --name wine -v ${PWD}/data:/app/data -v ${PWD}/metrics:/app/metrics wine

      - name: send report
        run: |
          git fetch --prune          
          echo "# Metrics\n" > report.md
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md

      - name: cleanup
        run: docker rm wine
