name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        run: |
          # Your ML workflow goes here
          docker build -t wine .

          docker run --name wine wine 

          docker cp wine:/app/metrics/metrics.json metrics/metrics.json
          git fetch --prune
          
          echo "\n##Metrics\n" >> report.md
          dvc metrics diff --show-md master >> report.md

          cml-send-comment report.md
