name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: |
          git fetch --prune
          docker build -t wine .

      - name: run
        run: docker run --name wine -v ${PWD}/data:/app/data -v ${PWD}/metrics:/app/metrics wine

      - name: send report
        run: |
          docker cp wine:/app/report.md report.md 
          cml-send-comment report.md

      - name: cleanup
        run: docker rm wine
